version: 2

sources:
    - name: DBT_DB
      description: 'Ceci est un exercice.'
      database: DBT_DB
      schema: PUBLIC
      tables:
        - name: COUNTRY_CODE
          description: 'Ceci est un test.'